# Generated by Django 5.1.7 on 2025-06-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id_address_userpreferences_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User Preferences', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
