# Generated by Django 5.1.11 on 2025-12-05 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email for non-logged-in users', max_length=254, null=True)),
                ('user_device', models.JSONField(default=dict)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, help_text='Final value set by admin after inspection', max_digits=12, null=True)),
                ('target_device_id', models.CharField(blank=True, default='', max_length=120)),
                ('target_device_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the swap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='orders_swap_user_id_4a69b9_idx'), models.Index(fields=['created_at'], name='orders_swap_created_1e71e6_idx')],
            },
        ),
    ]
